### ISSUE TITLE
AssertionError while running sentence_tokenizer.py

### ISSUE THREAD

**Issue by vidyap-xgboost** [arditoibryan/Projects#1]
```python
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1320: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py:92: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-27-5efddba8af37> in <module>()
----> 1 df = emoji_dataset(df, 5)

2 frames
/content/torchMoji/torchmoji/sentence_tokenizer.py in tokenize_sentences(self, sentences, reset_stats, max_sentences)
    117         # may filter the sentences etc.
    118         if not self.uses_custom_wordgen and not self.ignore_sentences_with_only_custom:
--> 119             assert len(sentences) == next_insert
    120         else:
    121             # adjust based on actual tokens received

AssertionError:
```

I keep getting this error when I try to run on a dataset which has more than 1996 rows/values in a list. I am running your notebook on a Colab. Here is the [link](https://colab.research.google.com/drive/1_WBgkg9v898FSlf0P9Vp8YZUhgmZXW9J?usp=sharing).

The notebook stops exactly after 8 minutes of running.
Did you face the same problem? If so, please tell me the solution.

**Comment by arditobryan** [comment]
Thank you for reporting, let me look into it

**Comment by arditobryan** [comment]
In my experiments I reached more than 5000, so it is definitely not an issue with numbers. Can you send me a link to your dataset? Maybe I can isolate the issue and add a condition for errors.

**Comment by vidyap-xgboost** [comment]
> In my experiments I reached more than 5000, so it is definitely not an issue with numbers. Can you send me a link to your dataset? Maybe I can isolate the issue and add a condition for errors.

@arditoibryan Here is the [dataset](https://drive.google.com/file/d/1b4kU351FQ2CX7L4aHOwj38CSSNR5ghXA/view?usp=sharing).

**Comment by vidyap-xgboost** [comment]
> > In my experiments I reached more than 5000, so it is definitely not an issue with numbers. Can you send me a link to your dataset? Maybe I can isolate the issue and add a condition for errors.
> 
> @arditoibryan Here is the dataset

@arditoibryan I just checked. The particular row at 1997 is a next line, meaning, it just has `\n` in it. So, that should be the reason, right?

**Comment by arditobryan** [comment]
![image](https://user-images.githubusercontent.com/63985091/86537275-39d55e80-beee-11ea-9d38-842bca874c03.png)
Gotcha! In line 1997 '\n' returns an error crashing the entre datast
In fact, line 1998 runs good
Tonight I will upload a fix that in case of errors will keep running

Thank you for reporting. I suggest you to edit the line or just delete it.

**Comment by vidyap-xgboost** [comment]
> ![image](https://user-images.githubusercontent.com/63985091/86537275-39d55e80-beee-11ea-9d38-842bca874c03.png)
> Gotcha! In line 1997 '\n' returns an error crashing the entre datast
> In fact, line 1998 runs good
> Tonight I will upload a fix that in case of errors will keep running
> 
> Thank you for reporting. I suggest you to edit the line or just delete it.

@arditoibryan Thank you!!! I've been trying to solve this bug for 3 days now and I simply forgot to check what exactly is on 1997th row. I don't understand why it didn't cross my mind until now.

Looking forward to your update in the notebook.
