### ISSUE TITLE
v is not defined

### ISSUE THREAD

**Issue by moku23** [arditoibryan/Projects#2]
Hello,
in 20200727_GOOG_Stock_Forecasts_2\Multivariate_LSTM_v.2.ipynb
`scaler_3, X = v.partition.scale('all_df', scaler='MinMaxScaler', df=X, to_float=True, return_df=True)`

i get `NameError: name 'v' is not defined`
in this version (Jul 2020) **v** is not set anywhere, but only in version of May with v = e.v
how can I set it in this case?
Thank you!
A presto
Mariano

**Comment by arditobryan** [comment]
Hi Mariano,

my bad, I used an old module I did for myself, now deprecated:

this is where you can download it (tf_dataset_extractor_v1.2.py)
https://github.com/arditoibryan/General

here you can find precise instructions on how to import it in your code:
https://medium.com/towards-artificial-intelligence/google-stock-predictions-using-an-lstm-neural-network-dbe785949a96

search for this piece of code in the article:
```
import sys
sys.path.append('/content/drive/My Drive/Colab Notebooks/TensorFlow 2.0/modules')
import pandas as pd
import tf_dataset_extractor as e
#import grapher_v1_1 as g
#import LSTM_creator_v1_0 as l
v = e.v
l = e.l
```

Have a great day,
Michelangiolo
